---
ingress:
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - host: circleci.immertec.red
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: app
            servicePort: 3000
