version: 2.1

orbs:
  python: circleci/python@1.2               # Needed to run s3 helm plugin.
  eks: circleci/aws-eks@1.1.0               # Used to control aws eks.
  helm: circleci/helm@1.2.0                 # Used to run helm commands.
  assume-role: deo-kalule/assume-role@0.2.0 # Used to assume an aws role.
  aws: circleci/aws-cli@2.0.3               # Needed to access s3.

jobs:
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - aws/install
      - helm/install-helm-client:
          version: v3.6.3
      - assume-role/assume-role:
          role-arn: $ROLE_ARN        # The AWS role arn that we are assuming.
          session-name: $CIRCLE_SHA1 # The commit SHA.
          profile: default           # The name of the AWS profile.
      # Authenticate kubernetes so that we can call kubectl commands.
      - eks/update-kubeconfig-with-authenticator:
          cluster-name: $CLUSTER_NAME # Kubernetes cluster name.
          aws-region: $AWS_REGION
      - run:
          name: Install helm s3 plugin
          command: |
            # Install S3 helm charts plugin used to host charts in S3.
            helm plugin install https://github.com/hypnoglow/helm-s3.git;
            # Initialize the ingress repository.
            helm s3 init $HELM_S3_BUCKET/ingress;
            # Add the local files in this project to populate the repo.
            helm repo add ingress $HELM_S3_BUCKET/ingress/;
      - run:
          name: Package and publish chart
          command: |
            # Package up the project files.
            helm package .;
            # Push the packaged helm repository to S3.
            helm s3 push ./ingress-0.0.1.tgz ingress;
            helm upgrade -f ingress.yaml ingress ingress/ingress --version 0.0.1 --install;

workflows:
  helm:
    jobs:
      - deploy
